# Generated by Django 6.1.1 on 2026-09-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
