# Generated by Django 6.1.1 on 2026-09-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0004_alter_video_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
