# Generated by Django 6.1.1 on 2026-09-13 11:20

import content_app.images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0005_video_thumbnail_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail_file',
            field=models.FileField(blank=True, upload_to='thumbnails/', validators=[content_app.images.validate_thumbnail_image]),
        ),
    ]
